# Generated by Django 2.1.2 on 2018-10-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181011_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('advert', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
