# Generated by Django 2.1.2 on 2018-10-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_advertimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertimages',
            name='thumb',
            field=models.ImageField(blank=True, default='Lighthouse.jpg', upload_to=''),
        ),
    ]
