# Generated by Django 2.1.2 on 2018-10-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181015_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert',
            new_name='AdvertImages',
        ),
    ]
