# Generated by Django 2.1.2 on 2018-10-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181016_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimages',
            name='advert',
            field=models.ImageField(blank=True, default='Lighthouse.jpg', null=True, upload_to='images/'),
        ),
    ]
