# Generated by Django 2.1.2 on 2018-10-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181019_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertimages',
            name='advert',
        ),
    ]
