# Generated by Django 2.1.2 on 2018-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_advertimages_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertimages',
            name='title',
        ),
        migrations.AlterField(
            model_name='advertimages',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
