# Generated by Django 2.1.2 on 2018-10-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_images_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
